---
- name: Init setup
  hosts: cloud1
  become: true
  vars:
    created_username: cloud1
  tasks:
    - name: Create a new regular user
      user:
        name: "{{ created_username }}"
        state: present
        create_home: true

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure that a base set of software packages are installed
      apt:
        name:
          - ufw
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - rsync
        state: latest
        lock_timeout: 120

    - name: Remove old packages from the cache
      apt:
        autoclean: yes
        lock_timeout: 120

    - name: Remove dependencies that are no longer needed
      apt:
        autoremove: yes
        purge: yes
        lock_timeout: 120

