FROM debian:bullseye-slim@sha256:9058862a1be84689bd13292549ba981364f85ff99e50a612f94b188ac69db137

LABEL org.opencontainers.image.source=https://github.com/hboissel/cloud-1

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install nginx -y
 
COPY conf/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/ssl

RUN getent group www-data || addgroup -g 82 www-data

RUN adduser -D -H -u 82 -G www-data -s /sbin/nologin www-data

RUN mkdir -p /var/run/nginx \
 && mkdir -p /var/www/wordpress \
 && chmod 755 /var/www/wordpress \
 && chown -R www-data:www-data /var/www/wordpress

ENTRYPOINT [ "nginx", "-g", "daemon off;" ] 
